# EightPoints GuzzleBundle
# A full list of configuration options can be found here:
# https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/configuration-reference.md
eight_points_guzzle:
    logging: true
    clients:
        api_gitlab:
            class: App\Client\GitlabApiClient
            base_url: '%env(string:GITLAB_SERVER_URL)%'
            options:
                headers:
                    Private-Token: '%env(string:GITLAB_TOKEN)%'
                    Accept: "application/json"
